### ISSUE TITLE
Meta Issue for tasks

### ISSUE THREAD

**Issue by rynoV** [rynoV/organizer#3]
A general overview of what needs to be done. Make checklists, then github will put a button next to each item when you hover to create a full issue.

# Frontend

For our UI to start it'll just be a list of items with statuses, and we can click on the items to change their statuses, or expand the items to get to their sublists.

# Backend

- [ ] Handle case of headers nested greater than 3 levels
- [ ] Add ids to org files and headers
- [ ] Add tags to headers
